-- MySQL Script generated by MySQL Workbench
-- Wed May 20 11:38:33 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema estudo_estoque_db
-- -----------------------------------------------------
-- Banco de dados voltado para fins de estudos, o readme.md tem todas as instrucoes necessarias
-- para o entendimento e fluxo do estudo.
-- Todas o estudo esta documento na primeira versao do projeto, pois ele e um piloto e ja parte
-- de uma premissa no qual o conhecimento ficou estagnado e portanto, precisar entender novos
-- conceitos para poder evoluir.

-- -----------------------------------------------------
-- Schema estudo_estoque_db
--
-- Banco de dados voltado para fins de estudos, o readme.md tem todas as instrucoes necessarias
-- para o entendimento e fluxo do estudo.
-- Todas o estudo esta documento na primeira versao do projeto, pois ele e um piloto e ja parte
-- de uma premissa no qual o conhecimento ficou estagnado e portanto, precisar entender novos
-- conceitos para poder evoluir.
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `estudo_estoque_db` ;
USE `estudo_estoque_db` ;

-- -----------------------------------------------------
-- Table `estudo_estoque_db`.`tb_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estudo_estoque_db`.`tb_usuario` (
)
ENGINE = InnoDB
COMMENT = 'Todas as tabelas serao documentas e em qual reame.md encontrar para o estudo\n\ntabela usuario: consistem nos seguintes campos, nos quais é minímo necessário para qualquer sistema\na tabela compoem dos campos\nnome, email, senha, role, avatar_url, access_token, refresh_token';


-- -----------------------------------------------------
-- Table `estudo_estoque_db`.`tb_regras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estudo_estoque_db`.`tb_regras` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(255) NULL,
  `ativo` TINYINT NULL DEFAULT 1,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idtb_regras_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB
COMMENT = 'tabela: destinada a definir regras e permissoes de usuario\ninicialmente a funcao dela é apenas definir qual é o tipo de usuário\num enum resolveria tranquilamente, porém desta forma abre espaço para outros estudos de caso\npor exemplo, temos os campos: ios_token, android_token, refresh_token\nEm um estudo, analisei que o correto nao deveria ter essa informacao na tabela usuarios, ela poderia estar\nem uma outra tabela por exemplo tb_tokens: onde que ficaria todos os tokens guardados\nPorque não normalizar o token ao invés de regras? Ai ficaria facil de mais, o estudo de caso\nEu vejo da seguinte forma, se eu posso normalizar uma tabela simples de regras de usuário, para eu normalizar\nos token o principio é o mesmo? se sim, como fazer da melhor forma, se não, quais as alternativas que possa ser faziado\n\n\n\n';


-- -----------------------------------------------------
-- Table `estudo_estoque_db`.`tb_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estudo_estoque_db`.`tb_usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `refresh_token` TEXT NULL,
  `android_token` TEXT NULL,
  `ios_token` TEXT NULL,
  `avatar_url` TEXT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NULL,
  `regra_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `fk_tb_usuarios_tb_regras1_idx` (`regra_id` ASC) VISIBLE,
  CONSTRAINT `fk_tb_usuarios_tb_regras1`
    FOREIGN KEY (`regra_id`)
    REFERENCES `estudo_estoque_db`.`tb_regras` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Todas as tabelas serao documentas e em qual reame.md encontrar para o estudo\n\ntabela usuario: consistem nos seguintes campos, nos quais é minímo necessário para qualquer sistema\na tabela compoem dos campos\nnome, email, senha, role, avatar_url, access_token, refresh_token';


-- -----------------------------------------------------
-- Table `estudo_estoque_db`.`tb_produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estudo_estoque_db`.`tb_produtos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  `preco_unitario` DECIMAL(10,2) NOT NULL,
  `ativo` TINYINT NULL DEFAULT 1 COMMENT 'tabela produtos: por padrao quantidade de estoque vem 1, não pode criar produto sem estoque\npor padroa: ativo vem true,\ntodas as tabelas por padrão, created_at - current_timestap\nativo, por padrão 0 (posso criar o produto e habilitar depois? claro que pode.\n',
  `estoque` INT NULL,
  `url_image` TEXT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT ON UPDATE CURRENT_TIMESTAMP COMMENT 'tabela produtos: todos os campos opicionais',
  `estoque` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_tb_produtos_tb_usuarios1_idx` (`estoque` ASC) VISIBLE,
  CONSTRAINT `fk_tb_produtos_tb_usuarios1`
    FOREIGN KEY (`estoque`)
    REFERENCES `estudo_estoque_db`.`tb_usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'tabela produtos: responsavel por armazenaros produtos, estoque,valor,ativo\nusuario_id: saber quem foi o usuário que fez alterações no produto\n\nlogica para quando adicionar/atualizar o irá altera apenas o updated_at e o id, assim criando espaço para uma possivel refatoracao e ter tabela de historicos';


-- -----------------------------------------------------
-- Table `estudo_estoque_db`.`tb_pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estudo_estoque_db`.`tb_pedidos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(45) NOT NULL,
  `status` ENUM('PENDENTE', 'APROVADO', 'RECUSADO') NULL DEFAULT 'PENDENTE',
  `valor_total` DECIMAL(10,2) NOT NULL,
  `observacao` VARCHAR(100) NULL,
  `created_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB
COMMENT = 'tabela pedidos: responsavel por salvar os pedidos\ntabela aux necessária: tb_produto_has_pedido e/ou tb_itens_pedidos \n\ntb_pedidos N:N tb_produtos';


-- -----------------------------------------------------
-- Table `estudo_estoque_db`.`tb_itens_do_pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estudo_estoque_db`.`tb_itens_do_pedido` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pedido_id` INT NOT NULL,
  `produto_id` INT NOT NULL,
  `quantidade` INT NOT NULL,
  `preco_unitario` DECIMAL(10,2) NOT NULL,
  `subtotal` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id`, `pedido_id`, `produto_id`),
  INDEX `fk_tb_produtos_has_tb_pedidos_tb_pedidos1_idx` (`pedido_id` ASC) VISIBLE,
  INDEX `fk_tb_produtos_has_tb_pedidos_tb_produtos1_idx` (`produto_id` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_tb_produtos_has_tb_pedidos_tb_produtos1`
    FOREIGN KEY (`produto_id`)
    REFERENCES `estudo_estoque_db`.`tb_produtos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_produtos_has_tb_pedidos_tb_pedidos1`
    FOREIGN KEY (`pedido_id`)
    REFERENCES `estudo_estoque_db`.`tb_pedidos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'tabela:tb_itens_do_pedido, responsavel por determinar que os itens pode estar em varios pedidos e que o pedido pode ter vários itens';


-- -----------------------------------------------------
-- Table `estudo_estoque_db`.`tb_movimentacaos_estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estudo_estoque_db`.`tb_movimentacaos_estoque` (
  `id` INT NOT NULL,
  `produto_id` INT NOT NULL,
  `usuario_id` INT NOT NULL,
  `tipo` ENUM('ENTRADA', 'SAIDA', 'AJUSTE', 'DEVOLUCAO') NOT NULL,
  `quantidade` INT NULL DEFAULT 1,
  `observacao` VARCHAR(255) NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_movimentacao_estoque_tb_produtos1_idx` (`produto_id` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_tb_movimentacaos_estoque_tb_usuarios1_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_tb_movimentacao_estoque_tb_produtos1`
    FOREIGN KEY (`produto_id`)
    REFERENCES `estudo_estoque_db`.`tb_produtos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_movimentacaos_estoque_tb_usuarios1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `estudo_estoque_db`.`tb_usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'tabela: voltada para a movimentacao de estoque e controle';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
